### PR TITLE
Test cleanup to simplify assertions and reduce parens

### PR DESCRIPTION
**Pull request by benjaminparker**

### CODE REVIEW

**Comment by PauloPortugal** [comment]
How did you replace all `must be(...)` with `mustBe` ?

What are the advantages? Simply a preferred syntax?

**Comment by PauloPortugal** [comment]
@leszeklorek @MaciejRewera @PatrykRudnicki @bethany-kish @NC-1234 What is your opinion on the test sugar syntax?

**Comment by PatrykRudnicki** [comment]
Using `must be()` has of course unnecessary parenthesis but it's closer to normal language. `mustBe` just shorter. That's all. Both approaches make the same, so it's just preferences. For me it doesn't matter what we will be using, but I'm not a fan of unnecessary changes that can be changed in two weeks, because someone will prefer `should be`. And after another two `shouldBe`...

**Comment by PatrykRudnicki** [comment]
I'll close it without removing branch, because probably we stopped discussion for now

**Pull request closed without merging**
