### PR TITLE
Ceds 1473 cache map removal

### PR DESCRIPTION
**Pull request by SteveSugden**

### CODE REVIEW

**Comment by PatrykRudnicki** [comment]
Can we squash it? and be sure that this branch is up to date based on the master

**Comment by SteveSugden** [comment]
I aways "squash"!  :-)

**Comment by PatrykRudnicki** [comment]
Great, but if you can please rebase, 9 commits and one line changed :)

**Comment by ed0906** [comment]
> Great, but if you can please rebase, 9 commits and one line changed :)

Squash and merge does the same thing whilst keeping the readability of the commit log in the PR

**Pull request merged**
