### PR TITLE
CEDS-1499 - country(s) of routing is optional

### PR DESCRIPTION
**Pull request by SteveSugden**

### CODE REVIEW

**Comment by PatrykRudnicki** [comment]
Please fix tests, there are tests for missing countries of routing

**Comment by SteveSugden** [comment]
Just spotted the failing tests.  Grrr.

**Comment by SteveSugden** [comment]
I've just run all tests with `precheck.sh` and everything passed.   Which tests did you mean @PatrykRudnicki ?

**Comment by PatrykRudnicki** [comment]
I saw in failing build, but we must have some test for it, if not we need to add it. In FormSpecs

**Comment by SteveSugden** [comment]
test this please

**Comment by PatrykRudnicki** [comment]
I see the failing tests:  
- when user put duplicated item *** FAILED ***
[info]     303 was not equal to 400 (DocumentProducedControllerSpec.scala:122)
[info]   - when user reach maximum amount of items *** FAILED ***
[info]     303 was not equal to 400 (DocumentProducedControllerSpec.scala:144)

**Comment by PatrykRudnicki** [comment]
So it's not related with your PR probably

**Comment by SteveSugden** [comment]
@PatrykRudnicki - good - thought I was going mad.   But you are right that some tests should be there.

**Pull request merged**
